# Generated by Django 3.0.6 on 2020-05-19 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200519_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_main_member',
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WaitUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wait_user', models.EmailField(max_length=254)),
                ('main_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
