# Generated by Django 3.0.6 on 2020-05-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='title',
            field=models.CharField(default=12, max_length=150),
            preserve_default=False,
        ),
    ]
