# Generated by Django 3.0.6 on 2020-05-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_mission_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='prize',
            field=models.IntegerField(default=0),
        ),
    ]
