# Generated by Django 3.0.6 on 2020-05-13 08:19

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', imagekit.models.fields.ProcessedImageField(upload_to='arti_intelli/pic_names')),
                ('title', models.TextField()),
            ],
        ),
    ]
