# Generated by Django 3.0.6 on 2020-05-13 08:24

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='pic_name',
            field=imagekit.models.fields.ProcessedImageField(upload_to='albums/pic_names'),
        ),
    ]
