# Generated by Django 3.0.6 on 2020-05-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20200513_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='albums.Photo')),
            ],
            bases=('albums.photo',),
        ),
    ]
